apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist-jrlb-jvavm
  labels:
    app: todolist
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todolist
  template:
    metadata:
      labels:
        app: todolist
    spec:
      containers:
      - name: todolist-jrlb-jvavm
        image: 325583868777.dkr.ecr.eu-central-1.amazonaws.com/jrlb-jvavm-repo:latest
        ports:
        - containerPort: 3000
